#ifndef __EFFECT_IDX_H_
#define __EFFECT_IDX_H_

enum {
    //MIC
    EFFECT_IDX_LOC_MIC_EQ,
    EFFECT_IDX_LOC_MIC_DRC,
    EFFECT_IDX_LOC_MIC_MAGIC,
    EFFECT_IDX_LOC_MIC_ECHO,
    EFFECT_IDX_MIX_DRC,
    EFFECT_IDX_MIX_EQ,

    //DAC
    EFFECT_IDX_MSC_DAC_EQ,
    EFFECT_IDX_MSC_DAC_DRC,

    //SCO
    EFFECT_IDX_MSC_MSBC_EQ,
    EFFECT_IDX_MSC_MSBC_DRC,
    EFFECT_IDX_MSC_CSVD_EQ,
    EFFECT_IDX_MSC_CVSD_DRC,

    //USB
    EFFECT_IDX_USB_MIC_EQ,
    EFFECT_IDX_USB_MIC_DRC,
    EFFECT_IDX_USB_MIC1_EQ,
    EFFECT_IDX_USB_MIC1_DRC,
    EFFECT_IDX_USB_MIC0_EQ,
    EFFECT_IDX_USB_MIC0_DRC,
    EFFECT_IDX_MAX_NB,
};

#endif // __EFFECT_IDX_H_
