#include "include.h"
#include "effect.h"


const effect_info_cfg_t effect_info[CFG_MAX] = {
	[CFG_MIX_DRC]  = {"CFG_MIX_DRC#", BUF_OFS_CFG_MIX_DRC,   BUF_LEN_OFS_CFG_MIX_DRC},
	[CFG_MAGIC]    = {"CFG_MAGIC###", BUF_OFS_CFG_MAGIC,     BUF_LEN_OFS_CFG_MAGIC},
	[CFG_ECHO]     = {"CFG_ECHO####", BUF_OFS_CFG_ECHO,      BUF_LEN_OFS_CFG_ECHO},
	[CFG_MSBC_EQ]  = {"CFG_MSBC_EQ#", BUF_OFS_CFG_MSBC_EQ,   BUF_LEN_OFS_CFG_MSBC_EQ},
	[CFG_MSBC_DRC] = {"CFG_MSBC_DRC", BUF_OFS_CFG_MSBC_DRC,  BUF_LEN_OFS_CFG_MSBC_DRC},
	[CFG_CSVD_EQ]  = {"CFG_CSVD_EQ#", BUF_OFS_CFG_CSVD_EQ,   BUF_LEN_OFS_CFG_CSVD_EQ},
	[CFG_CSVD_DRC] = {"CFG_CSVD_DRC", BUF_OFS_CFG_CSVD_DRC,  BUF_LEN_OFS_CFG_CSVD_DRC},
	[CFG_MIX_EQ]   = {"CFG_MIX_EQ##", BUF_OFS_CFG_MIX_EQ,    BUF_LEN_OFS_CFG_MIX_EQ},
	[CFG_MIC_EQ]   = {"CFG_MIC_EQ##", BUF_OFS_CFG_MIC_EQ,    BUF_LEN_OFS_CFG_MIC_EQ},
	[CFG_MIC_DRC]  = {"CFG_MIC_DRC#", BUF_OFS_CFG_MIC_DRC,   BUF_LEN_OFS_CFG_MIC_DRC},
	[CFG_DAC_DRC]  = {"CFG_DAC_DRC#", BUF_OFS_CFG_DAC_DRC,   BUF_LEN_OFS_CFG_DAC_DRC},
	[CFG_DAC_EQ]   = {"CFG_DAC_EQ##", BUF_OFS_CFG_DAC_EQ,    BUF_LEN_OFS_CFG_DAC_EQ},
	[CFG_USB_EQ]   = {"CFG_USB_EQ##", BUF_OFS_CFG_USB_EQ,    BUF_LEN_OFS_CFG_USB_EQ},
	[CFG_USB_DRC]  = {"CFG_USB_DRC#", BUF_OFS_CFG_USB_DRC,   BUF_LEN_OFS_CFG_USB_DRC},
	[CFG_USB1_DRC] = {"CFG_USB1_DRC", BUF_OFS_CFG_USB1_DRC,  BUF_LEN_OFS_CFG_USB1_DRC},
	[CFG_USB1_EQ]  = {"CFG_USB1_EQ#", BUF_OFS_CFG_USB1_EQ,   BUF_LEN_OFS_CFG_USB1_EQ},
	[CFG_USB0_DRC] = {"CFG_USB0_DRC", BUF_OFS_CFG_USB0_DRC,  BUF_LEN_OFS_CFG_USB0_DRC},
	[CFG_USB0_EQ]  = {"CFG_USB0_EQ#", BUF_OFS_CFG_USB0_EQ,   BUF_LEN_OFS_CFG_USB0_EQ},
};


/*模块初始化更新回调注册表 cv到应用层使用
const effect_update_callback_t effect_update_callback_tbl[CFG_MAX] = {
	[CFG_MIX_DRC]  = {NULL},
	[CFG_MAGIC]    = {NULL},
	[CFG_ECHO]     = {NULL},
	[CFG_MSBC_EQ]  = {NULL},
	[CFG_MSBC_DRC] = {NULL},
	[CFG_CSVD_EQ]  = {NULL},
	[CFG_CSVD_DRC] = {NULL},
	[CFG_MIX_EQ]   = {NULL},
	[CFG_MIC_EQ]   = {NULL},
	[CFG_MIC_DRC]  = {NULL},
	[CFG_DAC_DRC]  = {NULL},
	[CFG_DAC_EQ]   = {NULL},
	[CFG_USB_EQ]   = {NULL},
	[CFG_USB_DRC]  = {NULL},
	[CFG_USB1_DRC] = {NULL},
	[CFG_USB1_EQ]  = {NULL},
	[CFG_USB0_DRC] = {NULL},
	[CFG_USB0_EQ]  = {NULL},
};
*/